/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.11
 * Generated at: 2025-12-02 03:55:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.client;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/Users/smolevanataliia/Food-delivery-team8-blyat/target/food-delivery-0.0.1-SNAPSHOT.jar!/META-INF/c-1_2.tld", Long.valueOf(1649425098000L));
    _jspx_dependants.put("file:/Users/smolevanataliia/Food-delivery-team8-blyat/target/food-delivery-0.0.1-SNAPSHOT.jar", Long.valueOf(1764647670270L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Личный кабинет - Food Delivery</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\">\n");
      out.write("    <style>\n");
      out.write("        .tabs {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 10px;\n");
      out.write("            border-bottom: 2px solid #ddd;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("        }\n");
      out.write("        .tab-button {\n");
      out.write("            padding: 10px 20px;\n");
      out.write("            background: none;\n");
      out.write("            border: none;\n");
      out.write("            cursor: pointer;\n");
      out.write("            font-size: 16px;\n");
      out.write("            border-bottom: 3px solid transparent;\n");
      out.write("            transition: all 0.3s;\n");
      out.write("        }\n");
      out.write("        .tab-button.active {\n");
      out.write("            border-bottom-color: #007bff;\n");
      out.write("            color: #007bff;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("        .tab-content {\n");
      out.write("            display: none;\n");
      out.write("        }\n");
      out.write("        .tab-content.active {\n");
      out.write("            display: block;\n");
      out.write("        }\n");
      out.write("        .shops-grid, .products-grid {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));\n");
      out.write("            gap: 20px;\n");
      out.write("            margin-top: 20px;\n");
      out.write("        }\n");
      out.write("        .shop-card, .product-card {\n");
      out.write("            border: 1px solid #ddd;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 15px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: box-shadow 0.3s;\n");
      out.write("        }\n");
      out.write("        .shop-card:hover, .product-card:hover {\n");
      out.write("            box-shadow: 0 4px 12px rgba(0,0,0,0.15);\n");
      out.write("        }\n");
      out.write("        .product-card {\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("        }\n");
      out.write("        .product-price {\n");
      out.write("            font-size: 18px;\n");
      out.write("            font-weight: bold;\n");
      out.write("            color: #28a745;\n");
      out.write("            margin: 10px 0;\n");
      out.write("        }\n");
      out.write("        .product-actions {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 10px;\n");
      out.write("            margin-top: auto;\n");
      out.write("        }\n");
      out.write("        .btn-small {\n");
      out.write("            padding: 5px 10px;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("        .cart-items {\n");
      out.write("            margin-top: 20px;\n");
      out.write("        }\n");
      out.write("        .cart-item {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("            padding: 15px;\n");
      out.write("            border: 1px solid #ddd;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            margin-bottom: 10px;\n");
      out.write("        }\n");
      out.write("        .cart-item-info {\n");
      out.write("            flex: 1;\n");
      out.write("        }\n");
      out.write("        .cart-item-quantity {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 5px;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("        .cart-summary {\n");
      out.write("            background: #f8f9fa;\n");
      out.write("            padding: 20px;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            margin-top: 20px;\n");
      out.write("        }\n");
      out.write("        .summary-row {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            margin: 10px 0;\n");
      out.write("            font-size: 16px;\n");
      out.write("        }\n");
      out.write("        .summary-total {\n");
      out.write("            font-size: 20px;\n");
      out.write("            font-weight: bold;\n");
      out.write("            color: #28a745;\n");
      out.write("            border-top: 2px solid #ddd;\n");
      out.write("            padding-top: 10px;\n");
      out.write("            margin-top: 10px;\n");
      out.write("        }\n");
      out.write("        .profile-form {\n");
      out.write("            max-width: 500px;\n");
      out.write("            margin-top: 20px;\n");
      out.write("        }\n");
      out.write("        .form-group {\n");
      out.write("            margin-bottom: 15px;\n");
      out.write("        }\n");
      out.write("        .form-group label {\n");
      out.write("            display: block;\n");
      out.write("            margin-bottom: 5px;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("        .form-group input, .form-group textarea {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 10px;\n");
      out.write("            border: 1px solid #ddd;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("        .form-group textarea {\n");
      out.write("            resize: vertical;\n");
      out.write("            min-height: 100px;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <nav class=\"navbar\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <h1><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">Food Delivery</a></h1>\n");
      out.write("            <div class=\"nav-user\">\n");
      out.write("                <span>Добро пожаловать, ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("!</span>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\" class=\"btn btn-secondary\">Выход</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <main class=\"container\">\n");
      out.write("        <h1>Личный кабинет</h1>\n");
      out.write("\n");
      out.write("        <div class=\"tabs\">\n");
      out.write("            <button class=\"tab-button active\" onclick=\"switchTab('restaurants')\">🏪 Рестораны</button>\n");
      out.write("            <button class=\"tab-button\" onclick=\"switchTab('cart')\">🛒 Корзина</button>\n");
      out.write("            <button class=\"tab-button\" onclick=\"switchTab('profile')\">👤 Профиль</button>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Вкладка Рестораны -->\n");
      out.write("        <div id=\"restaurants\" class=\"tab-content active\">\n");
      out.write("            <h2>Доступные рестораны</h2>\n");
      out.write("\n");
      out.write("            <div class=\"category-filter\" style=\"margin-bottom: 20px;\">\n");
      out.write("                <label>Выберите категорию:</label>\n");
      out.write("                <select id=\"categoryFilter\" onchange=\"filterByCategory()\" style=\"padding: 10px; margin-left: 10px;\">\n");
      out.write("                    <option value=\"\">Все категории</option>\n");
      out.write("                    <option value=\"BAKERY\">Хлебобулочные</option>\n");
      out.write("                    <option value=\"MAIN_DISH\">Основные блюда</option>\n");
      out.write("                    <option value=\"DESSERT\">Десерты</option>\n");
      out.write("                    <option value=\"DRINK\">Напитки</option>\n");
      out.write("                    <option value=\"OTHER\">Другое</option>\n");
      out.write("                </select>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"shops-grid\" id=\"shopsContainer\">\n");
      out.write("                <p>Загрузка ресторанов...</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Вкладка Корзина -->\n");
      out.write("        <div id=\"cart\" class=\"tab-content\">\n");
      out.write("            <h2>Ваша корзина</h2>\n");
      out.write("            <div class=\"cart-items\" id=\"cartContainer\">\n");
      out.write("                <p>Корзина пуста</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"cart-summary\" id=\"cartSummary\" style=\"display:none;\">\n");
      out.write("                <div class=\"summary-row\">\n");
      out.write("                    <span>Количество товаров:</span>\n");
      out.write("                    <span id=\"cartCount\">0</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"summary-row\">\n");
      out.write("                    <span>Сумма:</span>\n");
      out.write("                    <span id=\"cartTotal\">0 ₽</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"summary-total\">\n");
      out.write("                    <div class=\"summary-row\">\n");
      out.write("                        <span>Итого:</span>\n");
      out.write("                        <span id=\"cartGrandTotal\">0 ₽</span>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <button class=\"btn btn-success\" style=\"width: 100%; margin-top: 20px;\">Оформить заказ</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Вкладка Профиль -->\n");
      out.write("        <div id=\"profile\" class=\"tab-content\">\n");
      out.write("            <h2>Мой профиль</h2>\n");
      out.write("            <form method=\"POST\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/client/update-profile\" class=\"profile-form\">\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"name\">Имя:</label>\n");
      out.write("                    <input type=\"text\" id=\"name\" name=\"name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"email\">Email:</label>\n");
      out.write("                    <input type=\"email\" id=\"email\" name=\"email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userEmail}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"phone\">Телефон:</label>\n");
      out.write("                    <input type=\"tel\" id=\"phone\" name=\"phone\" placeholder=\"89XXXXXXXXX\" required>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"country\">Страна:</label>\n");
      out.write("                    <input type=\"text\" id=\"country\" name=\"country\" placeholder=\"Россия\">\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"city\">Город:</label>\n");
      out.write("                    <input type=\"text\" id=\"city\" name=\"city\" placeholder=\"Москва\">\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"street\">Улица:</label>\n");
      out.write("                    <input type=\"text\" id=\"street\" name=\"street\" placeholder=\"Главная улица\">\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"building\">Здание:</label>\n");
      out.write("                    <input type=\"text\" id=\"building\" name=\"building\" placeholder=\"1\">\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"apartment\">Квартира:</label>\n");
      out.write("                    <input type=\"text\" id=\"apartment\" name=\"apartment\" placeholder=\"101\">\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary\">Сохранить</button>\n");
      out.write("            </form>\n");
      out.write("\n");
      out.write("            <div style=\"margin-top: 30px;\">\n");
      out.write("                <h3>Опасная зона</h3>\n");
      out.write("                <button onclick=\"if(confirm('Вы уверены?')) location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/client/deactivate'\" class=\"btn btn-danger\">\n");
      out.write("                    Деактивировать аккаунт\n");
      out.write("                </button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </main>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        function switchTab(tabName) {\n");
      out.write("            // Скрыть все вкладки\n");
      out.write("            document.querySelectorAll('.tab-content').forEach(tab => {\n");
      out.write("                tab.classList.remove('active');\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            // Деактивировать все кнопки\n");
      out.write("            document.querySelectorAll('.tab-button').forEach(btn => {\n");
      out.write("                btn.classList.remove('active');\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            // Показать выбранную вкладку\n");
      out.write("            document.getElementById(tabName).classList.add('active');\n");
      out.write("            event.target.classList.add('active');\n");
      out.write("\n");
      out.write("            // Загрузить данные если нужно\n");
      out.write("            if (tabName === 'restaurants') {\n");
      out.write("                loadShops();\n");
      out.write("            } else if (tabName === 'cart') {\n");
      out.write("                loadCart();\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function loadShops() {\n");
      out.write("            fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/shop/list-api')\n");
      out.write("                .then(response => response.json())\n");
      out.write("                .then(shops => {\n");
      out.write("                    let html = '';\n");
      out.write("                    if (shops.length === 0) {\n");
      out.write("                        html = '<p>Нет доступных ресторанов</p>';\n");
      out.write("                    } else {\n");
      out.write("                        shops.forEach(shop => {\n");
      out.write("                            html += `\n");
      out.write("                                <div class=\"shop-card\" onclick=\"viewShopProducts(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shop.shopId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\">\n");
      out.write("                                    <h3>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shop.naming}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\n");
      out.write("                                    <p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shop.description}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("                                    <p style=\"color: #666; font-size: 14px;\">📧 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shop.publicEmail}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("                                </div>\n");
      out.write("                            `;\n");
      out.write("                        });\n");
      out.write("                    }\n");
      out.write("                    document.getElementById('shopsContainer').innerHTML = html;\n");
      out.write("                })\n");
      out.write("                .catch(error => {\n");
      out.write("                    console.error('Ошибка загрузки ресторанов:', error);\n");
      out.write("                    document.getElementById('shopsContainer').innerHTML = '<p>Ошибка загрузки ресторанов</p>';\n");
      out.write("                });\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function viewShopProducts(shopId) {\n");
      out.write("            fetch(`");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products/by-shop?shopId=` + shopId)\n");
      out.write("                .then(response => response.json())\n");
      out.write("                .then(products => {\n");
      out.write("                    let html = '<h3>Продукты</h3><div class=\"products-grid\">';\n");
      out.write("                    if (products.length === 0) {\n");
      out.write("                        html += '<p>Нет продуктов</p>';\n");
      out.write("                    } else {\n");
      out.write("                        products.forEach(product => {\n");
      out.write("                            html += `\n");
      out.write("                                <div class=\"product-card\">\n");
      out.write("                                    <h4>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\n");
      out.write("                                    <p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.description}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("                                    <p style=\"color: #666; font-size: 12px;\">Вес: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.weight}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("g</p>\n");
      out.write("                                    <div class=\"product-price\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.price}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" ₽</div>\n");
      out.write("                                    <div class=\"product-actions\">\n");
      out.write("                                        <button onclick=\"addToCart(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.productId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('\'');
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.price}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\"\n");
      out.write("                                                class=\"btn btn-success btn-small\">+ Добавить</button>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            `;\n");
      out.write("                        });\n");
      out.write("                    }\n");
      out.write("                    html += '</div>';\n");
      out.write("                    document.getElementById('shopsContainer').innerHTML = html;\n");
      out.write("                })\n");
      out.write("                .catch(error => {\n");
      out.write("                    console.error('Ошибка загрузки продуктов:', error);\n");
      out.write("                });\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function addToCart(productId, productName, price) {\n");
      out.write("            fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart/add', {\n");
      out.write("                method: 'POST',\n");
      out.write("                headers: {\n");
      out.write("                    'Content-Type': 'application/x-www-form-urlencoded',\n");
      out.write("                },\n");
      out.write("                body: `productId=` + productId + `&quantity=1`\n");
      out.write("            })\n");
      out.write("            .then(response => response.json())\n");
      out.write("            .then(data => {\n");
      out.write("                alert('✅ ' + productName + ' добавлен в корзину');\n");
      out.write("                loadCart();\n");
      out.write("            })\n");
      out.write("            .catch(error => console.error('Ошибка:', error));\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function loadCart() {\n");
      out.write("            fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart/items-api')\n");
      out.write("                .then(response => response.json())\n");
      out.write("                .then(items => {\n");
      out.write("                    let html = '';\n");
      out.write("                    let total = 0;\n");
      out.write("                    let count = 0;\n");
      out.write("\n");
      out.write("                    if (items.length === 0) {\n");
      out.write("                        html = '<p>Корзина пуста</p>';\n");
      out.write("                        document.getElementById('cartSummary').style.display = 'none';\n");
      out.write("                    } else {\n");
      out.write("                        items.forEach(item => {\n");
      out.write("                            let itemTotal = item.price * item.quantity;\n");
      out.write("                            total += itemTotal;\n");
      out.write("                            count += item.quantity;\n");
      out.write("                            html += `\n");
      out.write("                                <div class=\"cart-item\">\n");
      out.write("                                    <div class=\"cart-item-info\">\n");
      out.write("                                        <h4>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\n");
      out.write("                                        <p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.price}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" ₽ × ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.quantity}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('=');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${itemTotal}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" ₽</p>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"cart-item-quantity\">\n");
      out.write("                                        <button onclick=\"updateQuantity(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.cartItemId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.quantity - 1}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\" class=\"btn btn-small\">−</button>\n");
      out.write("                                        <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.quantity}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("                                        <button onclick=\"updateQuantity(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.cartItemId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.quantity + 1}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\" class=\"btn btn-small\">+</button>\n");
      out.write("                                        <button onclick=\"removeFromCart(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.cartItemId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\" class=\"btn btn-danger btn-small\">✕ Удалить</button>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            `;\n");
      out.write("                        });\n");
      out.write("                        document.getElementById('cartSummary').style.display = 'block';\n");
      out.write("                        document.getElementById('cartCount').textContent = count;\n");
      out.write("                        document.getElementById('cartTotal').textContent = total + ' ₽';\n");
      out.write("                        document.getElementById('cartGrandTotal').textContent = total + ' ₽';\n");
      out.write("                    }\n");
      out.write("                    document.getElementById('cartContainer').innerHTML = html;\n");
      out.write("                })\n");
      out.write("                .catch(error => {\n");
      out.write("                    console.error('Ошибка загрузки корзины:', error);\n");
      out.write("                    document.getElementById('cartContainer').innerHTML = '<p>Ошибка загрузки корзины</p>';\n");
      out.write("                });\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function updateQuantity(cartItemId, newQuantity) {\n");
      out.write("            if (newQuantity < 1) {\n");
      out.write("                removeFromCart(cartItemId);\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart/update', {\n");
      out.write("                method: 'POST',\n");
      out.write("                headers: {\n");
      out.write("                    'Content-Type': 'application/x-www-form-urlencoded',\n");
      out.write("                },\n");
      out.write("                body: `cartItemId=` + cartItemId + `&quantity=` + newQuantity\n");
      out.write("            })\n");
      out.write("            .then(() => loadCart())\n");
      out.write("            .catch(error => console.error('Ошибка:', error));\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function removeFromCart(cartItemId) {\n");
      out.write("            fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart/remove?cartItemId=' + cartItemId, {\n");
      out.write("                method: 'POST'\n");
      out.write("            })\n");
      out.write("            .then(() => {\n");
      out.write("                alert('✅ Товар удален из корзины');\n");
      out.write("                loadCart();\n");
      out.write("            })\n");
      out.write("            .catch(error => console.error('Ошибка:', error));\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function filterByCategory() {\n");
      out.write("            const category = document.getElementById('categoryFilter').value;\n");
      out.write("            if (category) {\n");
      out.write("                fetch(`");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products/by-category?category=` + category)\n");
      out.write("                    .then(response => response.json())\n");
      out.write("                    .then(products => {\n");
      out.write("                        let html = '<div class=\"products-grid\">';\n");
      out.write("                        products.forEach(product => {\n");
      out.write("                            html += `\n");
      out.write("                                <div class=\"product-card\">\n");
      out.write("                                    <h4>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\n");
      out.write("                                    <p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.description}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("                                    <div class=\"product-price\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.price}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" ₽</div>\n");
      out.write("                                    <button onclick=\"addToCart(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.productId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('\'');
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.price}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\"\n");
      out.write("                                            class=\"btn btn-success\">+ Добавить</button>\n");
      out.write("                                </div>\n");
      out.write("                            `;\n");
      out.write("                        });\n");
      out.write("                        html += '</div>';\n");
      out.write("                        document.getElementById('shopsContainer').innerHTML = html;\n");
      out.write("                    })\n");
      out.write("                    .catch(error => console.error('Ошибка:', error));\n");
      out.write("            } else {\n");
      out.write("                loadShops();\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        // Загрузить рестораны при загрузке страницы\n");
      out.write("        window.addEventListener('load', loadShops);\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
