/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.11
 * Generated at: 2025-12-07 14:24:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.client;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/home/loopydoopy/IdeaProjects/Food-delivery-team8/target/food-delivery-0.0.1-SNAPSHOT.jar!/META-INF/c-1_2.tld", Long.valueOf(1649425098000L));
    _jspx_dependants.put("file:/home/loopydoopy/IdeaProjects/Food-delivery-team8/target/food-delivery-0.0.1-SNAPSHOT.jar", Long.valueOf(1765115429113L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Личный кабинет - Food Delivery</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\">\n");
      out.write("    <style>\n");
      out.write("        .tabs { display: flex; gap: 10px; border-bottom: 2px solid #ddd; margin-bottom: 20px; }\n");
      out.write("        .tab-button { padding: 10px 20px; background: none; border: none; cursor: pointer; font-size: 16px; border-bottom: 3px solid transparent; }\n");
      out.write("        .tab-button.active { border-bottom-color: #007bff; color: #007bff; font-weight: bold; }\n");
      out.write("        .tab-content { display: none; }\n");
      out.write("        .tab-content.active { display: block; }\n");
      out.write("        .shops-grid, .products-grid, .categories-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); gap: 16px; margin-top: 20px; }\n");
      out.write("        .shop-card, .product-card, .category-card { border: 1px solid #ddd; border-radius: 8px; padding: 15px; transition: box-shadow 0.2s; background: #fff; }\n");
      out.write("        .shop-card:hover, .product-card:hover, .category-card:hover { box-shadow: 0 4px 12px rgba(0,0,0,0.12); }\n");
      out.write("        .product-price { font-size: 18px; font-weight: bold; color: #28a745; margin: 10px 0; }\n");
      out.write("        .product-actions { display: flex; gap: 10px; margin-top: auto; }\n");
      out.write("        .btn-small { padding: 6px 10px; font-size: 13px; }\n");
      out.write("        .back-link { margin-top: 10px; display: inline-flex; align-items: center; color: #007bff; cursor: pointer; }\n");
      out.write("        .back-link span { margin-left: 6px; }\n");
      out.write("        .cart-items { margin-top: 20px; }\n");
      out.write("        .cart-item { display: flex; justify-content: space-between; align-items: center; padding: 15px; border: 1px solid #ddd; border-radius: 8px; margin-bottom: 10px; }\n");
      out.write("        .cart-summary { background: #f8f9fa; padding: 20px; border-radius: 8px; margin-top: 20px; }\n");
      out.write("        .summary-row { display: flex; justify-content: space-between; margin: 10px 0; font-size: 16px; }\n");
      out.write("        .summary-total { font-size: 20px; font-weight: bold; color: #23a340; border-top: 2px solid #ddd; padding-top: 10px; margin-top: 10px; }\n");
      out.write("        .empty-state { padding: 40px; text-align: center; color: #777; border: 1px dashed #ccc; border-radius: 8px; }\n");
      out.write("        .orders-list, .notifications-list { margin-top: 20px; display: flex; flex-direction: column; gap: 12px; }\n");
      out.write("        .order-card, .notification-card { border: 1px solid #ddd; border-radius: 8px; padding: 15px; background: #fff; transition: all 0.3s ease; position: relative; }\n");
      out.write("        .notification-card.unread { border-left: 4px solid #007bff; background: #f8f9ff; box-shadow: 0 2px 8px rgba(0,123,255,0.1); }\n");
      out.write("        .notification-card.unread strong { color: #007bff; }\n");
      out.write("        .notification-card.unread::before { content: ''; position: absolute; top: 15px; right: 15px; width: 10px; height: 10px; background: #dc3545; border-radius: 50%; border: 2px solid white; box-shadow: 0 0 0 1px #dc3545; }\n");
      out.write("        @keyframes markAsRead {\n");
      out.write("            0% { transform: scale(1); opacity: 1; }\n");
      out.write("            50% { transform: scale(1.2); opacity: 0.8; }\n");
      out.write("            100% { transform: scale(0); opacity: 0; }\n");
      out.write("        }\n");
      out.write("        .modal-overlay { position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.6); display: flex; justify-content: center; align-items: center; z-index: 1000; }\n");
      out.write("        .modal-content { background: white; padding: 30px; border-radius: 8px; max-width: 500px; width: 90%; max-height: 90vh; overflow-y: auto; }\n");
      out.write("        .modal-actions { display: flex; justify-content: flex-end; gap: 10px; margin-top: 20px; }\n");
      out.write("        .inactive-overlay { position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(255, 255, 255, 0.8); z-index: 999; display: flex; justify-content: center; align-items: center; text-align: center; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("<nav class=\"navbar\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <h1><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">Food Delivery</a></h1>\n");
      out.write("        <div class=\"nav-user\">\n");
      out.write("            <span>Добро пожаловать, ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("!</span>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\" class=\"btn btn-secondary\">Выход</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<main class=\"container\">\n");
      out.write("    <h1>Личный кабинет</h1>\n");
      out.write("\n");
      out.write("    <div class=\"tabs\">\n");
      out.write("        <button class=\"tab-button active\" data-tab=\"restaurants\" onclick=\"switchTab(event, 'restaurants')\">🏪 Рестораны</button>\n");
      out.write("        <button class=\"tab-button\" data-tab=\"cart\" onclick=\"switchTab(event, 'cart')\">🛒 Корзина</button>\n");
      out.write("        <button class=\"tab-button\" data-tab=\"profile\" onclick=\"switchTab(event, 'profile')\">👤 Профиль</button>\n");
      out.write("        <button class=\"tab-button\" data-tab=\"orders\" onclick=\"switchTab(event, 'orders')\">🧾 История заказов</button>\n");
      out.write("        <button class=\"tab-button\" data-tab=\"notifications\" onclick=\"switchTab(event, 'notifications')\">🔔 Уведомления</button>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div id=\"restaurants\" class=\"tab-content active\">\n");
      out.write("        <div id=\"shopListSection\">\n");
      out.write("            <h2>Доступные рестораны</h2>\n");
      out.write("            <div class=\"shops-grid\" id=\"shopsContainer\">\n");
      out.write("                <div class=\"empty-state\">Загрузка ресторанов...</div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div id=\"shopDetailsSection\" style=\"display:none;\">\n");
      out.write("            <div class=\"back-link\" onclick=\"showShopList()\">⬅ <span>К списку ресторанов</span></div>\n");
      out.write("            <h2 id=\"selectedShopName\"></h2>\n");
      out.write("            <p id=\"selectedShopInfo\"></p>\n");
      out.write("            <div>\n");
      out.write("                <h3>Категории</h3>\n");
      out.write("                <div class=\"categories-grid\" id=\"categoriesContainer\"></div>\n");
      out.write("            </div>\n");
      out.write("            <div>\n");
      out.write("                <h3>Продукты</h3>\n");
      out.write("                <div class=\"products-grid\" id=\"productsContainer\">\n");
      out.write("                    <div class=\"empty-state\">Выберите категорию, чтобы увидеть продукты.</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div id=\"cart\" class=\"tab-content\">\n");
      out.write("        <h2>Ваша корзина</h2>\n");
      out.write("        <div class=\"cart-items\" id=\"cartContainer\">\n");
      out.write("            <div class=\"empty-state\">Корзина пуста</div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"cart-summary\" id=\"cartSummary\" style=\"display:none;\">\n");
      out.write("            <div class=\"summary-row\"><span>Количество товаров:</span><span id=\"cartCount\">0</span></div>\n");
      out.write("            <div class=\"summary-row\"><span>Сумма:</span><span id=\"cartTotal\">0 ₽</span></div>\n");
      out.write("            <div class=\"summary-total\"><div class=\"summary-row\"><span>Итого:</span><span id=\"cartGrandTotal\">0 ₽</span></div></div>\n");
      out.write("            <button class=\"btn btn-danger\" style=\"width:100%; margin-top:10px;\" onclick=\"clearCart()\">Очистить корзину</button>\n");
      out.write("            <button class=\"btn btn-success\" style=\"width:100%; margin-top:10px;\" onclick=\"showCheckoutModal()\">Оформить заказ</button>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div id=\"profile\" class=\"tab-content\">\n");
      out.write("        <h2>Мой профиль</h2>\n");
      out.write("        <form method=\"POST\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/client/update-profile\" class=\"profile-form\">\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"name\">Имя:</label>\n");
      out.write("                <input type=\"text\" id=\"name\" name=\"name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"email\">Email:</label>\n");
      out.write("                <input type=\"email\" id=\"email\" name=\"email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userEmail}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"phone\">Телефон:</label>\n");
      out.write("                <input type=\"tel\" id=\"phone\" name=\"phone\" placeholder=\"89XXXXXXXXX\" required>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"country\">Страна:</label>\n");
      out.write("                <input type=\"text\" id=\"country\" name=\"country\" placeholder=\"Россия\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"city\">Город:</label>\n");
      out.write("                <input type=\"text\" id=\"city\" name=\"city\" placeholder=\"Москва\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"street\">Улица:</label>\n");
      out.write("                <input type=\"text\" id=\"street\" name=\"street\" placeholder=\"Главная улица\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"building\">Здание:</label>\n");
      out.write("                <input type=\"text\" id=\"building\" name=\"building\" placeholder=\"1\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"apartment\">Квартира:</label>\n");
      out.write("                <input type=\"text\" id=\"apartment\" name=\"apartment\" placeholder=\"101\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary\">Сохранить</button>\n");
      out.write("        </form>\n");
      out.write("        <div style=\"margin-top:30px;\">\n");
      out.write("            <h3>Опасная зона</h3>\n");
      out.write("            <form id=\"deactivateForm\" method=\"POST\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/client/deactivate\" style=\"display: inline;\">\n");
      out.write("                <button type=\"submit\" class=\"btn btn-danger\" onclick=\"return confirm('Вы уверены, что хотите деактивировать аккаунт?');\">Деактивировать аккаунт</button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div id=\"orders\" class=\"tab-content\">\n");
      out.write("        <h2>История заказов</h2>\n");
      out.write("        <div id=\"ordersContainer\" class=\"orders-list\">\n");
      out.write("            <div class=\"empty-state\">Загрузка заказов...</div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div id=\"notifications\" class=\"tab-content\">\n");
      out.write("        <h2>Уведомления</h2>\n");
      out.write("        <div style=\"text-align:right; margin-bottom:10px;\">\n");
      out.write("            <button class=\"btn btn-secondary\" onclick=\"markNotificationsRead()\">Отметить прочитанными</button>\n");
      out.write("        </div>\n");
      out.write("        <div id=\"notificationsContainer\" class=\"notifications-list\">\n");
      out.write("            <div class=\"empty-state\">Загрузка уведомлений...</div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</main>\n");
      out.write("\n");
      out.write("<div id=\"checkoutModal\" class=\"modal-overlay\" style=\"display:none;\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("        <h2>Подтверждение заказа</h2>\n");
      out.write("        <p>Пожалуйста, проверьте детали вашего заказа и адрес доставки.</p>\n");
      out.write("        <div id=\"modalOrderSummary\"></div>\n");
      out.write("        <form id=\"checkoutForm\">\n");
      out.write("            <h3>Адрес доставки</h3>\n");
      out.write("            <div class=\"info-grid\">\n");
      out.write("                <div class=\"form-group\"><label>Страна:</label><input type=\"text\" name=\"country\" required></div>\n");
      out.write("                <div class=\"form-group\"><label>Город:</label><input type=\"text\" name=\"city\" required></div>\n");
      out.write("                <div class=\"form-group\"><label>Улица:</label><input type=\"text\" name=\"street\" required></div>\n");
      out.write("                <div class=\"form-group\"><label>Здание:</label><input type=\"text\" name=\"building\" required></div>\n");
      out.write("                <div class=\"form-group\"><label>Квартира:</label><input type=\"text\" name=\"apartment\"></div>\n");
      out.write("                <div class=\"form-group\"><label>Подъезд:</label><input type=\"text\" name=\"entrance\"></div>\n");
      out.write("                <div class=\"form-group\"><label>Этаж:</label><input type=\"text\" name=\"floor\"></div>\n");
      out.write("                <div class=\"form-group\" style=\"grid-column: 1 / -1;\"><label>Комментарий:</label><textarea name=\"addressNote\"></textarea></div>\n");
      out.write("            </div>\n");
      out.write("            <h3>Оплата</h3>\n");
      out.write("            <select name=\"paymentMethod\" style=\"width:100%; margin:10px 0; padding:8px;\">\n");
      out.write("                <option value=\"CASH\">Оплата при получении</option>\n");
      out.write("                <option value=\"CARD\">Карта онлайн</option>\n");
      out.write("            </select>\n");
      out.write("        </form>\n");
      out.write("        <div class=\"modal-actions\">\n");
      out.write("            <button class=\"btn btn-secondary\" onclick=\"hideCheckoutModal()\">Отмена</button>\n");
      out.write("            <button class=\"btn btn-success\" onclick=\"confirmCheckout()\">Подтвердить и заказать</button>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    let currentShopId = null;\n");
      out.write("    const isInactive = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.clientStatus}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" === \"INACTIVE\";\n");
      out.write("\n");
      out.write("    function switchTab(evt, tabName) {\n");
      out.write("        document.querySelectorAll('.tab-content').forEach(tab => tab.classList.remove('active'));\n");
      out.write("        document.querySelectorAll('.tab-button').forEach(btn => btn.classList.remove('active'));\n");
      out.write("        document.getElementById(tabName).classList.add('active');\n");
      out.write("        evt.target.classList.add('active');\n");
      out.write("        if (tabName === 'restaurants') loadShops();\n");
      out.write("        if (tabName === 'cart') loadCart();\n");
      out.write("        if (tabName === 'orders') loadOrders();\n");
      out.write("        if (tabName === 'notifications') loadNotifications();\n");
      out.write("        if (tabName === 'profile') loadProfileData();\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function showShopList() {\n");
      out.write("        document.getElementById('shopDetailsSection').style.display = 'none';\n");
      out.write("        document.getElementById('shopListSection').style.display = 'block';\n");
      out.write("        currentShopId = null;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function escapeHtml(str) {\n");
      out.write("        if (!str) return '';\n");
      out.write("        return str\n");
      out.write("            .replace(/&/g, '&amp;')\n");
      out.write("            .replace(/</g, '&lt;')\n");
      out.write("            .replace(/>/g, '&gt;')\n");
      out.write("            .replace(/\"/g, '&quot;')\n");
      out.write("            .replace(/'/g, '&#39;');\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function renderShopCard(shop) {\n");
      out.write("        const card = document.createElement('div');\n");
      out.write("        card.className = 'shop-card';\n");
      out.write("        card.addEventListener('click', () => openShop(shop.shopId, shop.naming || ''));\n");
      out.write("        card.innerHTML = '' +\n");
      out.write("            '<h3>' + escapeHtml(shop.naming || '') + '</h3>' +\n");
      out.write("            '<p>' + escapeHtml(shop.description || '') + '</p>' +\n");
      out.write("            '<p style=\"color:#666;font-size:13px;\">📧 ' + escapeHtml(shop.publicEmail || '—') + ' | ☎ ' + escapeHtml(shop.publicPhone || '—') + '</p>' +\n");
      out.write("            '<p style=\"font-size:12px;color:#999;\">Тип: ' + escapeHtml(shop.type || '—') + '</p>';\n");
      out.write("        return card;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function renderProductCard(product) {\n");
      out.write("        const card = document.createElement('div');\n");
      out.write("        card.className = 'product-card';\n");
      out.write("        card.innerHTML = '' +\n");
      out.write("            '<h4>' + escapeHtml(product.name || '') + '</h4>' +\n");
      out.write("            '<p>' + escapeHtml(product.description || '') + '</p>' +\n");
      out.write("            '<p style=\"color:#666;font-size:12px;\">Вес: ' + (product.weight || 0) + ' г</p>' +\n");
      out.write("            '<div class=\"product-price\">' + (product.price || 0) + ' ₽</div>' +\n");
      out.write("            '<div class=\"product-actions\">' +\n");
      out.write("            '  <button class=\"btn btn-success btn-small\" ' + (isInactive ? 'disabled' : '') + '>+ Добавить</button>' +\n");
      out.write("            '</div>';\n");
      out.write("        card.querySelector('button').addEventListener('click', () => addToCart(product.productId, product.name || ''));\n");
      out.write("        return card;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function renderCartItem(item) {\n");
      out.write("        const wrapper = document.createElement('div');\n");
      out.write("        wrapper.className = 'cart-item';\n");
      out.write("        wrapper.innerHTML = '' +\n");
      out.write("            '<div>' +\n");
      out.write("            '  <strong>' + escapeHtml(item.name || '') + '</strong>' +\n");
      out.write("            '  <p>' + item.price + ' ₽ × ' + item.quantity + ' = ' + (item.price * item.quantity) + ' ₽</p>' +\n");
      out.write("            '</div>' +\n");
      out.write("            '<div class=\"cart-item-quantity\">' +\n");
      out.write("            '  <button class=\"btn btn-small\" ' + (isInactive ? 'disabled' : '') + '>−</button>' +\n");
      out.write("            '  <span>' + item.quantity + '</span>' +\n");
      out.write("            '  <button class=\"btn btn-small\" ' + (isInactive ? 'disabled' : '') + '>+</button>' +\n");
      out.write("            '  <button class=\"btn btn-danger btn-small\" ' + (isInactive ? 'disabled' : '') + '>×</button>' +\n");
      out.write("            '</div>';\n");
      out.write("        const buttons = wrapper.querySelectorAll('button');\n");
      out.write("        buttons[0].addEventListener('click', () => updateQuantity(item.cartItemId, item.quantity - 1));\n");
      out.write("        buttons[1].addEventListener('click', () => updateQuantity(item.cartItemId, item.quantity + 1));\n");
      out.write("        buttons[2].addEventListener('click', () => removeFromCart(item.cartItemId));\n");
      out.write("        return wrapper;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function loadShops() {\n");
      out.write("        fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/shop/list-api')\n");
      out.write("            .then(r => r.json())\n");
      out.write("            .then(shops => {\n");
      out.write("                const container = document.getElementById('shopsContainer');\n");
      out.write("                container.innerHTML = '';\n");
      out.write("                if (!shops.length) {\n");
      out.write("                    container.innerHTML = '<div class=\"empty-state\">Нет доступных ресторанов</div>';\n");
      out.write("                    return;\n");
      out.write("                }\n");
      out.write("                shops.forEach(shop => container.appendChild(renderShopCard(shop)));\n");
      out.write("            })\n");
      out.write("            .catch(() => {\n");
      out.write("                document.getElementById('shopsContainer').innerHTML = '<div class=\"empty-state\">Ошибка загрузки ресторанов</div>';\n");
      out.write("            });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function openShop(shopId, shopName) {\n");
      out.write("        currentShopId = shopId;\n");
      out.write("        document.getElementById('shopListSection').style.display = 'none';\n");
      out.write("        document.getElementById('shopDetailsSection').style.display = 'block';\n");
      out.write("        document.getElementById('selectedShopName').innerText = shopName;\n");
      out.write("        document.getElementById('selectedShopInfo').innerText = 'Выберите категорию, чтобы увидеть продукты.';\n");
      out.write("        loadCategories(shopId);\n");
      out.write("        document.getElementById('productsContainer').innerHTML = '<div class=\"empty-state\">Загрузка категорий...</div>';\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function loadCategories(shopId) {\n");
      out.write("        fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products/categories?shopId=' + shopId)\n");
      out.write("            .then(r => r.json())\n");
      out.write("            .then(categories => {\n");
      out.write("                const container = document.getElementById('categoriesContainer');\n");
      out.write("                container.innerHTML = '';\n");
      out.write("                if (!categories.length) {\n");
      out.write("                    container.innerHTML = '<div class=\"empty-state\">Категории не найдены</div>';\n");
      out.write("                    document.getElementById('productsContainer').innerHTML = '<div class=\"empty-state\">Нет продуктов</div>';\n");
      out.write("                    return;\n");
      out.write("                }\n");
      out.write("                categories.forEach(cat => {\n");
      out.write("                    const card = document.createElement('div');\n");
      out.write("                    card.className = 'category-card';\n");
      out.write("                    card.innerHTML = '<strong>' + translateCategory(cat) + '</strong>';\n");
      out.write("                    card.addEventListener('click', () => loadProducts(shopId, cat));\n");
      out.write("                    container.appendChild(card);\n");
      out.write("                });\n");
      out.write("                loadProducts(shopId, categories[0]);\n");
      out.write("            })\n");
      out.write("            .catch(() => {\n");
      out.write("                document.getElementById('categoriesContainer').innerHTML = '<div class=\"empty-state\">Ошибка загрузки категорий</div>';\n");
      out.write("            });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function loadProducts(shopId, category) {\n");
      out.write("        document.getElementById('productsContainer').innerHTML = '<div class=\"empty-state\">Загрузка продуктов...</div>';\n");
      out.write("        fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products/by-shop?shopId=' + shopId + '&category=' + encodeURIComponent(category))\n");
      out.write("            .then(r => r.json())\n");
      out.write("            .then(products => {\n");
      out.write("                const container = document.getElementById('productsContainer');\n");
      out.write("                container.innerHTML = '';\n");
      out.write("                if (!products.length) {\n");
      out.write("                    container.innerHTML = '<div class=\"empty-state\">Нет продуктов в этой категории</div>';\n");
      out.write("                    return;\n");
      out.write("                }\n");
      out.write("                products.forEach(product => container.appendChild(renderProductCard(product)));\n");
      out.write("            })\n");
      out.write("            .catch(() => {\n");
      out.write("                document.getElementById('productsContainer').innerHTML = '<div class=\"empty-state\">Ошибка загрузки продуктов</div>';\n");
      out.write("            });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function addToCart(productId, productName) {\n");
      out.write("        fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart/add', {\n");
      out.write("            method: 'POST',\n");
      out.write("            headers: { 'Content-Type': 'application/x-www-form-urlencoded' },\n");
      out.write("            body: 'productId=' + productId + '&quantity=1'\n");
      out.write("        })\n");
      out.write("            .then(r => r.json())\n");
      out.write("            .then(() => {\n");
      out.write("                alert('✅ ' + productName + ' добавлен в корзину');\n");
      out.write("                loadCart();\n");
      out.write("            })\n");
      out.write("            .catch(() => alert('Не удалось добавить товар в корзину'));\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function clearCart() {\n");
      out.write("        if (confirm('Вы уверены, что хотите очистить корзину?')) {\n");
      out.write("            fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart/clear', { method: 'POST' })\n");
      out.write("                .then(loadCart);\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function loadCart() {\n");
      out.write("        fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart/items-api')\n");
      out.write("            .then(r => r.json())\n");
      out.write("            .then(data => {\n");
      out.write("                const items = data.items || [];\n");
      out.write("                const container = document.getElementById('cartContainer');\n");
      out.write("                container.innerHTML = '';\n");
      out.write("                if (!items.length) {\n");
      out.write("                    container.innerHTML = '<div class=\"empty-state\">Корзина пуста</div>';\n");
      out.write("                    document.getElementById('cartSummary').style.display = 'none';\n");
      out.write("                    return;\n");
      out.write("                }\n");
      out.write("                let total = data.total || 0;\n");
      out.write("                let count = 0;\n");
      out.write("                items.forEach(item => {\n");
      out.write("                    count += item.quantity;\n");
      out.write("                    container.appendChild(renderCartItem(item));\n");
      out.write("                });\n");
      out.write("                document.getElementById('cartSummary').style.display = 'block';\n");
      out.write("                document.getElementById('cartCount').innerText = count;\n");
      out.write("                document.getElementById('cartTotal').innerText = total + ' ₽';\n");
      out.write("                document.getElementById('cartGrandTotal').innerText = total + ' ₽';\n");
      out.write("            })\n");
      out.write("            .catch(() => {\n");
      out.write("                document.getElementById('cartContainer').innerHTML = '<div class=\"empty-state\">Ошибка загрузки корзины</div>';\n");
      out.write("            });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function updateQuantity(cartItemId, newQuantity) {\n");
      out.write("        if (newQuantity < 1) {\n");
      out.write("            removeFromCart(cartItemId);\n");
      out.write("            return;\n");
      out.write("        }\n");
      out.write("        fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart/update', {\n");
      out.write("            method: 'POST',\n");
      out.write("            headers: { 'Content-Type': 'application/x-www-form-urlencoded' },\n");
      out.write("            body: 'cartItemId=' + cartItemId + '&quantity=' + newQuantity\n");
      out.write("        }).then(loadCart);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function removeFromCart(cartItemId) {\n");
      out.write("        fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart/remove', {\n");
      out.write("            method: 'POST',\n");
      out.write("            headers: { 'Content-Type': 'application/x-www-form-urlencoded' },\n");
      out.write("            body: 'cartItemId=' + cartItemId\n");
      out.write("        }).then(loadCart);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function translateCategory(cat) {\n");
      out.write("        const map = { BAKERY: 'Хлебобулочные', MAIN_DISH: 'Основные блюда', DESSERT: 'Десерты', DRINK: 'Напитки', OTHER: 'Другое' };\n");
      out.write("        return map[cat] || cat;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function showCheckoutModal() {\n");
      out.write("        fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/client/profile-api') // Предполагается новый API для данных клиента\n");
      out.write("            .then(r => r.json())\n");
      out.write("            .then(client => {\n");
      out.write("                const form = document.getElementById('checkoutForm');\n");
      out.write("                const address = client.address || {};\n");
      out.write("                form.country.value = address.country || '';\n");
      out.write("                form.city.value = address.city || '';\n");
      out.write("                form.street.value = address.street || '';\n");
      out.write("                form.building.value = address.building || '';\n");
      out.write("                form.apartment.value = address.apartment || '';\n");
      out.write("                form.entrance.value = address.entrance || '';\n");
      out.write("                form.floor.value = address.floor || '';\n");
      out.write("                form.addressNote.value = address.addressNote || '';\n");
      out.write("            });\n");
      out.write("\n");
      out.write("        const summary = document.getElementById('modalOrderSummary');\n");
      out.write("        summary.innerHTML = document.getElementById('cartContainer').innerHTML;\n");
      out.write("        summary.querySelectorAll('button').forEach(b => b.remove()); // Убираем кнопки управления из саммари\n");
      out.write("\n");
      out.write("        document.getElementById('checkoutModal').style.display = 'flex';\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function hideCheckoutModal() {\n");
      out.write("        document.getElementById('checkoutModal').style.display = 'none';\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function confirmCheckout() {\n");
      out.write("        const form = document.getElementById('checkoutForm');\n");
      out.write("        const formData = new FormData(form);\n");
      out.write("        const body = new URLSearchParams(formData).toString();\n");
      out.write("\n");
      out.write("        fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart/checkout', {\n");
      out.write("            method: 'POST',\n");
      out.write("            headers: { 'Content-Type': 'application/x-www-form-urlencoded' },\n");
      out.write("            body: body\n");
      out.write("        })\n");
      out.write("        .then(r => r.json())\n");
      out.write("        .then(data => {\n");
      out.write("            if (data.error) {\n");
      out.write("                alert('Ошибка: ' + data.error);\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("            alert('Заказ #' + data.orderId + ' оформлен. Статус: ' + data.status);\n");
      out.write("            hideCheckoutModal();\n");
      out.write("            loadCart();\n");
      out.write("            loadOrders();\n");
      out.write("        })\n");
      out.write("        .catch(() => alert('Не удалось оформить заказ'));\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function loadOrders() {\n");
      out.write("        fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/client/orders-api')\n");
      out.write("            .then(r => r.json())\n");
      out.write("            .then(orders => {\n");
      out.write("                console.log('Orders received:', orders);\n");
      out.write("                const container = document.getElementById('ordersContainer');\n");
      out.write("                if (!orders || !orders.length) {\n");
      out.write("                    container.innerHTML = '<div class=\"empty-state\">Заказов пока нет</div>';\n");
      out.write("                    return;\n");
      out.write("                }\n");
      out.write("                container.innerHTML = orders.map(order => {\n");
      out.write("                    const orderId = order.id || 'N/A';\n");
      out.write("                    const status = order.status || 'Неизвестно';\n");
      out.write("                    const total = order.total || 0;\n");
      out.write("                    const createdAt = order.createdAt || '';\n");
      out.write("                    const items = order.items || [];\n");
      out.write("                    const itemsHtml = items.map(item => {\n");
      out.write("                        const name = escapeHtml(item.name || 'Неизвестный товар');\n");
      out.write("                        const qty = item.quantity || 0;\n");
      out.write("                        const price = item.price || 0;\n");
      out.write("                        return name + ' × ' + qty + ' — ' + price + ' ₽';\n");
      out.write("                    }).join('<br>');\n");
      out.write("\n");
      out.write("                    const disabledAttr = (orderId === 'N/A' || isInactive) ? 'disabled' : '';\n");
      out.write("\n");
      out.write("                    return '<div class=\"order-card\">' +\n");
      out.write("                        '<div style=\"display:flex; justify-content:space-between;\">' +\n");
      out.write("                        '<strong>Заказ #' + orderId + '</strong>' +\n");
      out.write("                        '<span>' + escapeHtml(createdAt) + '</span>' +\n");
      out.write("                        '</div>' +\n");
      out.write("                        '<p>Статус: <strong>' + escapeHtml(status) + '</strong></p>' +\n");
      out.write("                        '<p>Сумма: <strong>' + total + ' ₽</strong></p>' +\n");
      out.write("                        '<div class=\"order-items\">' + (itemsHtml || 'Нет товаров') + '</div>' +\n");
      out.write("                        '<button class=\"btn btn-primary btn-small\" onclick=\"repeatOrder(' + orderId + ')\" ' + disabledAttr + '>Повторить</button>' +\n");
      out.write("                        '</div>';\n");
      out.write("                }).join('');\n");
      out.write("            })\n");
      out.write("            .catch((err) => {\n");
      out.write("                console.error('Failed to load orders:', err);\n");
      out.write("                document.getElementById('ordersContainer').innerHTML = '<div class=\"empty-state\">Ошибка загрузки заказов</div>';\n");
      out.write("            });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function loadNotifications() {\n");
      out.write("        fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/client/notifications-api')\n");
      out.write("            .then(r => r.json())\n");
      out.write("            .then(list => {\n");
      out.write("                console.log('Notifications received:', list);\n");
      out.write("                const container = document.getElementById('notificationsContainer');\n");
      out.write("                if (!list || !list.length) {\n");
      out.write("                    container.innerHTML = '<div class=\"empty-state\">Уведомлений нет</div>';\n");
      out.write("                    return;\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                container.innerHTML = list.map(n => {\n");
      out.write("                    const type = n.type || 'Уведомление';\n");
      out.write("                    const message = n.message || '';\n");
      out.write("                    const createdAt = n.createdAt || n.timestamp || '';\n");
      out.write("                    const readFlag = n.isRead;\n");
      out.write("                    const isRead = (typeof readFlag === 'boolean' ? readFlag : n.read) ? '' : 'unread';\n");
      out.write("                    console.log('Notification:', type, 'isRead:', n.isRead, 'class:', isRead);\n");
      out.write("\n");
      out.write("                    return '<div class=\"notification-card ' + isRead + '\" data-is-read=\"' + n.isRead + '\">' +\n");
      out.write("                        '<div style=\"display:flex; justify-content:space-between;\">' +\n");
      out.write("                        '<strong>' + escapeHtml(type) + '</strong>' +\n");
      out.write("                        '<span>' + escapeHtml(createdAt) + '</span>' +\n");
      out.write("                        '</div>' +\n");
      out.write("                        '<p>' + escapeHtml(message) + '</p>' +\n");
      out.write("                        '</div>';\n");
      out.write("                }).join('');\n");
      out.write("            })\n");
      out.write("            .catch((err) => {\n");
      out.write("                console.error('Failed to load notifications:', err);\n");
      out.write("                document.getElementById('notificationsContainer').innerHTML = '<div class=\"empty-state\">Ошибка загрузки уведомлений</div>';\n");
      out.write("            });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function markNotificationsRead() {\n");
      out.write("        fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/client/notifications/readAll', {\n");
      out.write("            method: 'POST'\n");
      out.write("        })\n");
      out.write("            .then(r => {\n");
      out.write("                if (!r.ok) {\n");
      out.write("                    alert('Не удалось отметить уведомления как прочитанные');\n");
      out.write("                    return;\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                const btn = document.querySelector('button[onclick=\"markNotificationsRead()\"]');\n");
      out.write("                if (btn) {\n");
      out.write("                    const originalText = btn.textContent;\n");
      out.write("                    btn.textContent = '✓ Отмечено!';\n");
      out.write("                    btn.disabled = true;\n");
      out.write("                    setTimeout(() => {\n");
      out.write("                        btn.textContent = originalText;\n");
      out.write("                        btn.disabled = false;\n");
      out.write("                    }, 2000);\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                document.querySelectorAll('.notification-card.unread').forEach(card => {\n");
      out.write("                    card.classList.remove('unread');\n");
      out.write("                    card.style.animation = 'markAsRead 0.5s ease-out';\n");
      out.write("                });\n");
      out.write("\n");
      out.write("                setTimeout(loadNotifications, 500);\n");
      out.write("            })\n");
      out.write("            .catch(() => alert('Ошибка сети при попытке отметить уведомления как прочитанные'));\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function loadProfileData() {\n");
      out.write("        fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/client/profile-api')\n");
      out.write("            .then(r => r.json())\n");
      out.write("            .then(client => {\n");
      out.write("                const form = document.querySelector('#profile .profile-form');\n");
      out.write("                form.name.value = client.name || '';\n");
      out.write("                form.email.value = client.email || '';\n");
      out.write("                form.phone.value = client.phone || '';\n");
      out.write("                const address = client.address || {};\n");
      out.write("                form.country.value = address.country || '';\n");
      out.write("                form.city.value = address.city || '';\n");
      out.write("                form.street.value = address.street || '';\n");
      out.write("                form.building.value = address.building || '';\n");
      out.write("                form.apartment.value = address.apartment || '';\n");
      out.write("            });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function repeatOrder(orderId) {\n");
      out.write("        console.log('repeatOrder called with orderId:', orderId);\n");
      out.write("        if (!orderId || orderId === 'undefined') {\n");
      out.write("            alert('Ошибка: не удалось определить ID заказа');\n");
      out.write("            console.error('orderId is undefined or invalid:', orderId);\n");
      out.write("            return;\n");
      out.write("        }\n");
      out.write("        fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/client/orders/repeat', {\n");
      out.write("            method: 'POST',\n");
      out.write("            headers: { 'Content-Type': 'application/x-www-form-urlencoded' },\n");
      out.write("            body: 'orderId=' + orderId\n");
      out.write("        })\n");
      out.write("            .then(r => r.json())\n");
      out.write("            .then(data => {\n");
      out.write("                if (data.error) {\n");
      out.write("                    alert('Ошибка: ' + data.error);\n");
      out.write("                    return;\n");
      out.write("                }\n");
      out.write("                alert('Товары заказа #' + orderId + ' добавлены в корзину');\n");
      out.write("                loadCart();\n");
      out.write("                const cartTabBtn = document.querySelector('.tab-button[data-tab=\"cart\"]');\n");
      out.write("                if (cartTabBtn) {\n");
      out.write("                    cartTabBtn.click();\n");
      out.write("                }\n");
      out.write("            })\n");
      out.write("            .catch((err) => {\n");
      out.write("                console.error('Failed to repeat order:', err);\n");
      out.write("                alert('Не удалось повторить заказ');\n");
      out.write("            });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    window.addEventListener('load', () => {\n");
      out.write("        loadShops();\n");
      out.write("        loadOrders();\n");
      out.write("        loadNotifications();\n");
      out.write("        if (isInactive) {\n");
      out.write("            document.querySelectorAll('button, input, select, textarea').forEach(el => {\n");
      out.write("                if (!el.closest('.inactive-overlay')) el.disabled = true;\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/jsp/client/home.jsp(47,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.clientStatus == 'INACTIVE'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("    <div class=\"inactive-overlay\">\n");
          out.write("        <div>\n");
          out.write("            <h2>Аккаунт деактивирован</h2>\n");
          out.write("            <p>Вы не можете совершать покупки. Обратитесь в поддержку для восстановления.</p>\n");
          out.write("            <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/logout\" class=\"btn btn-primary\">Выйти</a>\n");
          out.write("        </div>\n");
          out.write("    </div>\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
