/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.11
 * Generated at: 2025-12-02 22:39:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class courier_005fearnings_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/Users/smolevanataliia/Food-delivery-team8-blyat/target/food-delivery-0.0.1-SNAPSHOT.jar!/META-INF/c-1_2.tld", Long.valueOf(1649425098000L));
    _jspx_dependants.put("file:/Users/smolevanataliia/Food-delivery-team8-blyat/target/food-delivery-0.0.1-SNAPSHOT.jar", Long.valueOf(1764715091245L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Заработок - Food Delivery</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"container\">\n");
      out.write("    <header>\n");
      out.write("        <h1>Заработок</h1>\n");
      out.write("        <p>Курьер: <span id=\"courierName\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.courier.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></p>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/courier/dashboard\" class=\"btn btn-secondary\">Назад к панели</a>\n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("    <div class=\"earnings-summary\">\n");
      out.write("        <h2>Общий заработок: <span id=\"totalEarnings\">0</span> руб.</h2>\n");
      out.write("        <h2>Заработок за сегодня: <span id=\"todayEarnings\">0</span> руб.</h2>\n");
      out.write("        <h2>Текущий баланс: <span id=\"currentBalance\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.courier.currentBalance}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span> руб.</h2>\n");
      out.write("        <button id=\"withdrawBtn\" class=\"btn btn-warning\">Вывести деньги</button>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"earnings-details\">\n");
      out.write("        <h2>Детали заработка</h2>\n");
      out.write("        <table class=\"earnings-table\">\n");
      out.write("            <thead>\n");
      out.write("                <tr>\n");
      out.write("                    <th>Дата</th>\n");
      out.write("                    <th>Заказ</th>\n");
      out.write("                    <th>Сумма</th>\n");
      out.write("                </tr>\n");
      out.write("            </thead>\n");
      out.write("            <tbody id=\"earningsTableBody\">\n");
      out.write("            </tbody>\n");
      out.write("        </table>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Modal for withdrawal -->\n");
      out.write("    <div id=\"withdrawModal\" class=\"modal\" style=\"display:none;\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <span class=\"close\">&times;</span>\n");
      out.write("            <h2>Вывод средств</h2>\n");
      out.write("            <p>Текущий баланс: <span id=\"modalBalance\">0</span> руб.</p>\n");
      out.write("            <form id=\"withdrawForm\">\n");
      out.write("                <label for=\"withdrawAmount\">Сумма для вывода:</label>\n");
      out.write("                <input type=\"number\" id=\"withdrawAmount\" name=\"amount\" min=\"1\" required>\n");
      out.write("                <button type=\"submit\" class=\"btn btn-success\">Подтвердить вывод</button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("let courierId = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.courier.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\n");
      out.write("\n");
      out.write("loadEarningsDetails();\n");
      out.write("\n");
      out.write("document.getElementById('withdrawBtn').addEventListener('click', () => {\n");
      out.write("    document.getElementById('withdrawModal').style.display = 'block';\n");
      out.write("    document.getElementById('modalBalance').textContent = document.getElementById('currentBalance').textContent;\n");
      out.write("});\n");
      out.write("document.querySelector('.close').addEventListener('click', () => {\n");
      out.write("    document.getElementById('withdrawModal').style.display = 'none';\n");
      out.write("});\n");
      out.write("document.getElementById('withdrawForm').addEventListener('submit', withdrawEarnings);\n");
      out.write("\n");
      out.write("function loadEarningsDetails() {\n");
      out.write("    fetch('/courier/today-history')\n");
      out.write("    .then(response => response.json())\n");
      out.write("    .then(orders => {\n");
      out.write("        const tbody = document.getElementById('earningsTableBody');\n");
      out.write("        tbody.innerHTML = '';\n");
      out.write("        let total = 0;\n");
      out.write("        orders.forEach(order => {\n");
      out.write("            const tr = document.createElement('tr');\n");
      out.write("            const date = new Date(order.updatedAt).toLocaleDateString();\n");
      out.write("            const amount = 100; // Mock\n");
      out.write("            total += amount;\n");
      out.write("            tr.innerHTML = `\n");
      out.write("                <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${date}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("                <td>Заказ #");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${order.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("                <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${amount}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" руб.</td>\n");
      out.write("            `;\n");
      out.write("            tbody.appendChild(tr);\n");
      out.write("        });\n");
      out.write("        document.getElementById('todayEarnings').textContent = total + ' руб.';\n");
      out.write("        document.getElementById('totalEarnings').textContent = total + ' руб.'; // For simplicity\n");
      out.write("    });\n");
      out.write("}\n");
      out.write("\n");
      out.write("function withdrawEarnings(event) {\n");
      out.write("    event.preventDefault();\n");
      out.write("    const amount = document.getElementById('withdrawAmount').value;\n");
      out.write("    fetch('/courier/withdraw', {\n");
      out.write("        method: 'POST'\n");
      out.write("    }).then(response => {\n");
      out.write("        if (response.ok) {\n");
      out.write("            alert(`Вывод денег выполнен: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${amount}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" руб.`);\n");
      out.write("            document.getElementById('withdrawModal').style.display = 'none';\n");
      out.write("            document.getElementById('withdrawForm').reset();\n");
      out.write("            location.reload(); // Reload to update balance\n");
      out.write("        } else {\n");
      out.write("            alert('Ошибка при выводе денег');\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
